# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Strauss' index page
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Strauss"
  avatar : "/assets/images/stss-photo.png"
  bio    : "Computer Engineer (B.Sc.). Master of Electronic and Computer Engineering (M.Sc.) ITA - Brazilian Aeronautics Institute of Technology."
  links:
    - label: "Website"
      icon: "fa-sharp fa-solid fa-blog"
      url: "https://stra-uss.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stra-uss"
    - label: "Linkedin"
      icon: "fab fa-linkedin fa-fw"
      url: "https://www.linkedin.com/in/strauss-cunha-carvalho-1a601a15/"
    - label: "kaggle"
      icon: "fa-brands fa-kaggle"
      url: "https://www.kaggle.com/strausswedgeoak"
    - label: "Research Gate"
      icon: "fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Strauss-Carvalho"
    - label: "Lattes"
      icon: "fa-thin fa-atom-simple"
      url: "http://lattes.cnpq.br/4915404310911390"
    - label: "OrcId"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/"
    - label: "e-Mail"
      icon: "fa-sharp fa-solid fa-envelope-circle-check"
      url: "strausswedgeoak@outlook.com"


  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"

footer:
  links:

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stra-uss"
    - label: "Linkedin"
      icon: "fab fa-linkedin fa-fw"
      url: "https://www.linkedin.com/in/strauss-cunha-carvalho-1a601a15/"
    - label: "kaggle"
      icon: "fab fa-kaggle fa-2x"
      url: "https://www.kaggle.com/strausswedgeoak"

  # - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
